### ISSUE TITLE
Max Property limit reached

### ISSUE THREAD

**Issue by vinod83k** [Azure-Samples/Azure-Time-Series-Insights#17]
> Please provide us with the following information:
> ---------------------------------------------------------------
We have a requirement to hold data for about 4000 to 6000 sensors. And we found about the different pricing tiers that S1 - 600, S2- 800 and PAYG - 1000 properties only. Please suggest as how we can have more that 1000 properties in TSI environment?

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by shreyasharmamsft** [comment]
@vinod83k property count limit refers to the number of properties you can send in an event payload (i.e. the number of columns stored by TSI). 

In Gen2 (PAYG version), we have a [Time Series Model](https://docs.microsoft.com/en-us/azure/time-series-insights/concepts-model-overview). Each sensor would be represented as an instance in TSM. We have a limit of 1 million instances. 

Hope that helps!
