### ISSUE TITLE
(S1/S2) How to fetch more than 10000 records from Azure Time Series in one API call?

### ISSUE THREAD

**Issue by RK-Rahul** [Azure-Samples/Azure-Time-Series-Insights#3]
I am developing one application where I am pushing sensor telemetries @ 1 second.

I want to export all telemetries for a Date range and the record will be then definitely more than 10000.

As per the documentation API can return only 10000 records(because that is the max limit) in the response so how can I get all records against the search criteria ?

**Comment by yeskarthik** [comment]
**For S1/S2 environments**

Currently the API can only return 10000 events in one call. When you do a /events call - Top by time ($ts), you can make a subsequent call by setting the "from" timestamp in the searchspan as the largest timestamp in the previous response.
