### ISSUE TITLE
Azure TimeSeries call returns  Internal server error. Please retry your request later

### ISSUE THREAD

**Issue by zainuvk** [Azure-Samples/Azure-Time-Series-Insights#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Create Azure TSI and publish sensor data for a time period  (Say "from": "2019-02-16T06:00:00Z",
      "to": "2019-02-16T07:15:00Z"

Query these results from API:

https://xxxxx-xxxx-xxx-xxx-xxx.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview&timeout=PT20S

Give appropriate value for Authorization header

 In request body give timestamp for which value doesn't exist

{
  "aggregateSeries": {
    "searchSpan": {
      "from": "2019-02-16T07:15:00Z",
      "to": "2019-02-16T07:30:00Z"
    },
    "timeSeriesId": [
      "**YourDeviceID**"
    ],
    "interval": "PT2M",
    "inlineVariables": {
      "temperatureC": {
        "kind": "numeric",
        "value": {
          "tsx": "$event.[temperatureC]"
        },
        "filter": null,
        "aggregation": {
          "tsx": "avg($value)"
        }
      },
      "humidity": {
        "kind": "numeric",
        "value": {
          "tsx": "$event.[humidity]"
        },
        "filter": null,
        "aggregation": {
          "tsx": "avg($value)"
        }
      }
    },
    "projectedVariables": [
      "temperatureC",
      "humidity"
    ]
  }
}

This would result in  Internal Server Error with status code 500
{"error":{"code":"InternalServerError","message":"Internal server error. Please retry your request later."}}

If I change 
  "from": "2019-02-16T07:15:00Z",
      "to": "2019-02-16T07:30:00Z"

to

  "from": "2019-02-16T06:00:00Z",
      "to": "2019-02-16T07:15:00Z"

The same API calls returns the results as expected.

### Any log messages given by the failure
> {"error":{"code":"InternalServerError","message":"Internal server error. Please retry your request later."}}

Sharing few of my request-id details for failures:
x-ms-request-id: a7635826-694d-4d2d-a1e5-a1da553c5341
Date: Sun, 17 Feb 2019 14:59:59 GMT

x-ms-request-id: edcff2c1-09ec-4a8a-9e33-be51fc5637f9
Date: Sun, 17 Feb 2019 14:58:59 GMT

x-ms-request-id: 766d4191-0c08-43ec-a28f-0ab94ff848ae
Date: Sun, 17 Feb 2019 14:56:32 GMT

The successful ones which returned values

x-ms-request-id: a98ea7b1-c2a2-47d7-a976-800e2d5b7573
Date: Sun, 17 Feb 2019 14:59:29 GMT

x-ms-request-id: 9a5218c5-1718-4493-b37f-53bf6a026046
Date: Sun, 17 Feb 2019 14:57:27 GMT

### Expected/desired behavior
>Shoudn't this call result in status 204 with header : no_content to be returned

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>Windows 10

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by zainuvk** [comment]
The same kind of call to eventSchema API works as expected.

 https://xxxx-xxxx-xxxx-xxxx-xxx.env.timeseries.azure.com/eventSchema?api-version=2018-11-01-preview&timeout=PT20S

For input parameter of
{
     "searchSpan": {
      "from": "2019-02-16T07:15:00Z",
      "to": "2019-02-16T07:30:00Z"
    }
}

the result is 

HTTP/1.1 **200 OK**
Content-Type: application/json
Server: Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
x-ms-request-id: de4f7dec-3a7c-4dab-8555-cec3601e9af6
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-ms-request-id,x-ms-continuation
Date: Sun, 17 Feb 2019 15:32:36 GMT
Content-Length: 17
**{"properties":[]}**

This looks like a good way of handling empty data when compared with timeseries/query.

**Comment by dmdenmsft** [comment]
We are working on the fix, it will be available shortly.

**Comment by yeskarthik** [comment]
This has been fixed and deployed.
